import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionsProvider from "@/components/SessionsProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionsProvider session={session}>{children}</SessionsProvider>
      </body>
    </html>
  );
}
